---
title: "Willingness to aromatic plants with mosquito repellent properties?"
output_dir: docs
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
```

Column {data-width=200}
-----------------------------------------------------------------------

### Input

```{r}
selectInput("a","Gender",choices = c("","Male","Female"))
selectInput("b","District",choices = c("","Badulla","Batticaloa", "Hambantota", "Kurunegala", "Matara", "Rathnapura"))
numericInput("c", "Age", 20, min = 1, max = 90)
selectInput("d","Education",choices = c("","PD (Passed Degree)","PA (Passed AL)", "PO (Passed O/L)", "P10 (Passed grade 10)", "P6 (Passed grade 5)", "NS (No schooling)"))
numericInput("e", "Income", 0, min = 0, max = 100000000)
numericInput("f", "Number of non-income family generating members", 0, min = 0, max = 100000000)
selectInput("g","Agronomics crops availability",choices = c("","Yes","No"))
numericInput("h", "Number of agri-contributing family members", 0, min = 0, max = 100000000)
numericInput("i", "Number of agri-contributing employees", 0, min = 0, max = 100000000)
numericInput("i", "Land size", 0, min = 0, max = 100000000)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Outcome


```{r}
library(tibble)
library(randomForest)
Gender <- reactive(input$a)
District <- reactive(input$b)
Age <- reactive(input$c)
Education <- reactive(input$d)
Income <- reactive(input$e)
#renderText(gender())
renderTable(tibble(Gender = factor(c(Gender())), 
District = factor(c(District())),
Age = c(Age()),
Education = factor(c(Education())),
Income = c(Income())


                       ))
```


```{r}
invisFun <- renderText({ invisible("Probability") })
invisFun()

```

